name: video-producer
description: Generates and uploads a YouTube video from a timeline JSON.
entrypoint: python3 scripts/video_producer.py $DATE
language: python

env:
  YOUTUBE_CLIENT_ID: $YOUTUBE_CLIENT_ID
  YOUTUBE_CLIENT_SECRET: $YOUTUBE_CLIENT_SECRET
  YOUTUBE_REFRESH_TOKEN: $YOUTUBE_REFRESH_TOKEN
